name: "Pull request documentation"
on: 
  pull_request

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install packages
      run: |
        pip install -r docs/requirements.txt
        pip install .

    - name: Build documentation
      run: |
        cd docs
        make html

    - uses: actions/upload-artifact@v2
      with:
        name: DocumentationHTML
        path: docs/build/html/
