name: "Pull request documentation"
on: 
  pull_request

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install packages
      run: |
        pip install .[doc]

    - name: Build documentation
      run: |
        cd docs
        make html

    - uses: actions/upload-artifact@v4
      with:
        name: DocumentationHTML
        path: docs/build/html/